export default [
  {
    id: 'mafamille',
    title: 'Ma Famille',
    description:
      'Mafa Group is a local organization of food industry located in Can Tho City. ',
    size: 2,
    responsibilities: [
      'Design UI/UX and implement the solution based on the customer requirements.',
      'Using VueJS to create the website.',
      'Be responsible for the deployment of the website on the Amazon Web Service Platform.',
    ],
    technologies: ['vue-dot-js', 'spring', 'mongodb', 'amazonaws'],
    position: 'Team Leader, Frontend Developer',
    imgs: [require('../assets/img/mafamile.jpg')],
    url: 'http://mafagroup.vn',
    github: '',
    isPermited: false,
  },
  {
    id: 'se-department',
    title: 'Can Tho University - Software Engrineering Department Website',
    description:
      'SE Website is used for introducing about Software Engrineering Department of Can Tho University. Beside, it is also used for the AUN-QA.',
    size: 4,
    responsibilities: [
      'Design UI/UX and implement the solution based on the customer requirements.',
      'Using VueJS to create the website.',
    ],
    technologies: [
      'vue-dot-js',
      'sass',
      'tailwindcss',
      'node-dot-js',
      'postgresql',
    ],
    position: 'Team Leader, Frontend Developer',
    imgs: [require('../assets/img/se.png')],
    url: 'http://se.cit.ctu.edu.vn',
    github: '',
    isPermited: false,
  },
  {
    id: 'unicorn',
    title: 'Unicorn Helpdesk System',
    description:
      'A helpdesk system provides you fully functions. It allows users submit theirs issue tickets, get assigned and fixed by techniciasns. It aslo have an android app besides this web app',
    size: 4,
    responsibilities: [
      'Design UI/UX and implement the solution based on the customer requirements.',
      'Using VueJS to create the website.',
    ],
    technologies: ['vue-dot-js', 'sass', 'spring', 'mongodb'],
    position: 'Team Leader, Front end Developer',
    imgs: [require('../assets/img/helpdesk.png')],
    url: 'https://unicornhelpdesk.netlify.app/',
    github: 'https://github.com/ngthuongdoan/helpdesk',
    isPermited: true,
  },
  {
    id: 'Schooling',
    title: 'Schooling',
    description:
      'This is the first website of my Web Development career for a Subject. It allows users to create multiple courses, assigns to a lecturer, create study events, etc. All of that will be visualized on a Timetable, which using FullCalendar.js',
    size: 1,
    responsibilities: [
      'Create all of its documents such as: Software Specification, Software Design,...',
      'Using NodeJS to build a server side rendering website based on MVC structure',
      '',
    ],
    technologies: ['html5', 'css3', 'javascript', 'node-dot-js', 'mysql'],
    position: 'Full Stack Developer',
    imgs: [require('../assets/img/sm3.png')],
    url: '',
    github: 'https://github.com/ngthuongdoan/StudyManagement',
    isPermited: true,
  },
  {
    id: 'mrvans',
    title: 'MR.VANS',
    description:
      'MR.VANS is a website for local start-up in the office lunch industry located in Ho Chi Minh City. ',
    size: 2,
    responsibilities: [
      'Design UI/UX and implement the solution based on the customer requirements.',
      'Database design and provide to backend developer.',
      'Using VueJS to create the website.',
      'Be responsible for the deployment of the website on the Google Cloud Platform.',
    ],
    technologies: ['vue-dot-js', 'spring', 'mongodb', 'googlecloud'],
    position: 'Team Leader, Frontend Developer',
    imgs: [require('../assets/img/mrvans.jpg')],
    url: 'http://mrvans.vn',
    github: '',
    isPermited: false,
  },
]
