# .github/workflows/deploy.yml

name: Deploy Next.js Static Site to VPS

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm install -f # Or yarn install, pnpm install, etc.

      - name: Build and Export Next.js Project
        # This step first builds the Next.js project (creating .next)
        # then exports it to static files (creating the 'out' directory).
        run: |
          npm run build
          npm run export
        env:
          NODE_ENV: production

      - name: Deploy 'out' directory to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0 # Action to connect and execute commands via SSH
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }} # Use port 22 by default, or your custom port
          # The 'script' command will be executed on the remote VPS
          script: |
            # Define the target directory on your VPS.
            # public_html is the standard document root for cPanel.
            TARGET_DIR="/home/${{ secrets.SSH_USERNAME }}/public_html"

            echo "Ensuring target directory exists: $TARGET_DIR"
            mkdir -p $TARGET_DIR

            echo "Removing old files from $TARGET_DIR for a clean deployment..."
            # WARNING: This command removes ALL files and subdirectories
            # from the TARGET_DIR. Ensure TARGET_DIR is correct!
            rm -rf $TARGET_DIR/*
            mkdir -p $TARGET_DIR/out # Ensure the 'out' directory exists
            echo "Transferring static files from 'out' directory to $TARGET_DIR..."
            # Use rsync to efficiently transfer files.
            # './out/' refers to the directory created by 'next export' on the GitHub Actions runner.
            # $TARGET_DIR/ refers to the destination on your VPS.
            rsync -avz --delete ./out/ $TARGET_DIR/

            echo "Deployment complete to $TARGET_DIR!"

